dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: floating-spire-85196
  strategy: git
  api_key:
    secure: lqUzdO6uktGAHJF2IkE6QkoWTgf1d2GIua/Zz3emKB+5Yh90fF5cYFrivroB0b8lflurq+8m38W3999Gb7wHwmpsXIlrEMkPQlCFV+WIdHkWyF8i/59pi1NqqqfD7HHJqEn3Hr8jc4ZaR6BJK6GGopsu3Y9e/+yjSfY7P3FygCQeX25twCG2Hzws/KmEHNaKRZ4njvSuEehLJqEQPEHlZVulqfjjb9owxE7z3rAfxH4Q3FB+jeGdNJYTcR1vpP0nptQk2t1+rQGzAPbg2YE7x+zRdSE1yUE5lHSX6l+L3BFHOZ8Zhdxek3Lcvk7Gd8NU0Ct53aXOc0GTZuza7W5HM9b5c745Q37K+SWY+JxoN1CaXTbRq+dqKf6SpjR2rzH6V67HvnPr2FvvbjmYCE7KGBRt7V6xAQSAw+R6Yc+641AO80u/41aAsVxPD+SyrbPA6LfdQBirw78ir77xOgym73qfGCIYhn7jjaGD9hUlds17V3liasQYp4LKw6R784NlekVW8QtU3w1F4K9G9oFuSZ7ugAjlOZEa4M5Ur06usE2ltRWX+lZ69PI/aP66d2oWoHmeR6cqGZfewsgSPGslcZbUDcJuzVU0p6OZXcbMZs2hfKjf+CZ4zOmcs9qp0L9WdHOzeBkdAH2BQVJYhnUc7hTOsmHol7YSR9vCPATvOoQ=
